// <auto-generated />
using System;
using GestorDeContactos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeContactos.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241103203134_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GestorDeContactos.Data.Models.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoContacto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroFijoContacto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumeroTelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdContacto");

                    b.ToTable("Contactos");
                });
#pragma warning restore 612, 618
        }
    }
}
